################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= matrixMul
# Cuda source files (compiled with cudacc)
CUFILES		:= matrixMul.cu

################################################################################
# Rules and targets

include ../../common/common.mk

#~ all:
	#~ nvcc -I "/home/raul/NVIDIA_GPU_Computing_SDK/C/common/inc" -o matrixMul matrixMul.cu
