################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= matrixMul
# Cuda source files (compiled with cudacc)
CUFILES		:= matrixMul.cu

################################################################################
# Rules and targets

include ../../common/common.mk
